import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by `velite build`, not authored here.
    ".velite/**",
  ]),
  {
    // `components/ui` and `hooks` are vendored from the shadcn registry and are
    // rewritten by `shadcn add` / `shadcn update`. Fixing lint findings in place
    // would be lost on the next sync, so the rules that only fire inside that
    // generated code are relaxed for those paths alone.
    files: ["components/ui/**", "hooks/**"],
    rules: {
      "react-hooks/set-state-in-effect": "off",
      "react-hooks/refs": "off",
    },
  },
]);

export default eslintConfig;
