import createMiddleware from "next-intl/middleware"

import { routing } from "@/i18n/routing"

export default createMiddleware(routing)

/**
 * Skip locale resolution for everything that is not a page.
 *
 * `api`, `_next` and `_vercel` are framework paths, and `.*\..*` covers files
 * with an extension such as sitemap.xml. `cohort-card` is a locale-independent
 * image route: it renders the same badge whichever language you browse in, and
 * routing it through the proxy 307s the request away from the image. Metadata
 * routes generated by
 * `app/icon.tsx`, `app/apple-icon.tsx` and `app/[locale]/opengraph-image.tsx`
 * have no extension, so they are named explicitly. The locale-prefixed forms
 * are listed too: without them the proxy strips the default-locale prefix from
 * `/fr/opengraph-image` and the request 307s away from the generated image.
 *
 * Next parses this value at compile time, so it has to be an inline literal and
 * cannot be assembled from `routing.locales`. Extend both the bare and the
 * locale-prefixed alternations when adding a locale.
 */
export const config = {
  matcher: [
    "/((?!api|_next|_vercel|cohort-card|icon|apple-icon|opengraph-image|twitter-image|manifest|fr/(?:icon|apple-icon|opengraph-image|twitter-image|manifest)|en/(?:icon|apple-icon|opengraph-image|twitter-image|manifest)|.*\\..*).*)",
  ],
}
